/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: coremort (https://sketchfab.com/coremort)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-room-e49f71feb3ea470888993134ce746bd5
title: Lowpoly Room
*/
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";


const Room = (props: any) => {
  const groupRef = useRef<any>();
  const gltf = useGLTF("./models/lowpoly_room.glb");
  const { nodes } = gltf;
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            {nodes.Box010001.children.map((node: any) => (
              <mesh key={node.id} {...node} />
            ))}
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/lowpoly_room.glb");

export default Room;
